In [1]:
import numpy as np

In [13]:
def proj(a, b):
    return b*(np.dot(a, b)/np.dot(b,b))

def QR(A: np.array):
    n, m = A.shape

    Q = np.copy(A)
    R = np.zeros((m, m))

    for j in range(m):
        next = A[:,j]
        print(next)
        for i in range(j):
            b = Q[:,i]
            R[i,j] = np.dot(next, b)
            next = next-proj(next,b)
            print(next)
        print()
        R[j,j] = np.dot(next, next)
        Q[:,j] = next
    return Q, R
            

In [14]:
rng = np.random.default_rng()
a = rng.normal(size=(2, 2))
Q, R = np.linalg.qr(a)
a, Q, R

(array([[ 0.68329002, -0.69718395],
        [ 0.88929341,  0.04047867]]),
 array([[-0.60927269, -0.79296078],
        [-0.79296078,  0.60927269]]),
 array([[-1.12148474,  0.39267714],
        [ 0.        ,  0.57750207]]))

In [16]:
Q, R = QR(a)
Q, R, Q@R

[0.68329002 0.88929341]

[-0.69718395  0.04047867]
[-0.45793649  0.35185624]



(array([[ 0.68329002, -0.45793649],
        [ 0.88929341,  0.35185624]]),
 array([[ 1.25772803, -0.44038142],
        [ 0.        ,  0.33350864]]),
 array([[ 0.85939301, -0.45363401],
        [ 1.11848925, -0.2742812 ]]))