In [2]:
import numpy as np

In [3]:
def proj(a, b):
    return b*np.dot(a, b)

def QR(A: np.array):
    n, m = A.shape

    Q = np.zeros((n, m))
    R = np.zeros((m, m))

    for j in range(m):
        next = A[:,j]
        for i in range(j):
            b = Q[:,i]
            R[i,j] = np.dot(next, b)
            next = next-proj(next, b)
        R[j,j] = np.sqrt((next*next).sum())
        Q[:,j] = (next / R[j,j])
    return Q, R

In [4]:
A = np.array(((1, 2, 3), (5, 7, 1), (14, 22, 31)))
# Checking correctness of QR
Q, R = QR(A)
print("Expected: ", A, "\nGot: ", Q@R)

Expected:  [[ 1  2  3]
 [ 5  7  1]
 [14 22 31]] 
Got:  [[ 1.  2.  3.]
 [ 5.  7.  1.]
 [14. 22. 31.]]


In [5]:
def TriMNK(A: np.array, b: np.array):
    n = A.shape[0]

    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i], x))/A[i,i]

    return x


def MNK(A: np.array, b: np.array):
    Q, R = QR(A)
    b = np.transpose(Q)@b
    return Q, R, TriMNK(R, b)

In [6]:
A = np.array(((1, 2, 3), (5, 7, 1), (14, 22, 31)))
b = np.array((42, 239, 25))

expected = np.linalg.lstsq(A, b, rcond=None)[0]
Q, R, res = MNK(A, b)

print(f"Square matrix solution diff: {np.linalg.norm(res-expected)}")

Square matrix solution diff: 4.7406354875705706e-12


In [7]:
A = np.array(((1, 2), (5, 7), (14, 22)))
b = np.array((42, 239, 25))

expected = np.linalg.lstsq(A, b, rcond=None)[0]
Q, R, res = MNK(A, b)

print(f"Matrix with m>n solution diff: {np.linalg.norm(res-expected)}")

Matrix with m>n solution diff: 2.96459002365857e-12
